### ISSUE TITLE
npm ERR! code EAUDITNOLOCK

### ISSUE THREAD

**Issue by nenengherlina** [bugsounet/MMM-Hotword#128]
Hii.
I have some problem 

i use 
npm 6.13.4
Node v10.19.0 

I hope some one can help my problem. thank you

pi@raspberrypi:~ $ sudo apt-get install libmagic-dev libatlas-base-dev sox libsox-fmt-all mpg321 libasound2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsox-fmt-all is already the newest version (14.4.1-5+deb9u2).
sox is already the newest version (14.4.1-5+deb9u2).
libasound2-dev is already the newest version (1.1.3-5+rpt4).
The following package was automatically installed and is no longer required:
  realpath
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  gfortran gfortran-6 libatlas-dev libatlas3-base libaudio-scrobbler-perl
  libauthen-sasl-perl libblas-dev libconfig-inifiles-perl
  libencode-locale-perl libfile-listing-perl libfont-afm-perl
  libgfortran-6-dev libhtml-form-perl libhtml-format-perl libhtml-parser-perl
  libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl
  libhttp-daemon-perl libhttp-date-perl libhttp-message-perl
  libhttp-negotiate-perl libio-html-perl libio-socket-ssl-perl
  liblwp-mediatypes-perl liblwp-protocol-https-perl libmailtools-perl
  libnet-http-perl libnet-smtp-ssl-perl libnet-ssleay-perl libtimedate-perl
  liburi-perl libwww-perl libwww-robotrules-perl perl-openssl-defaults
Suggested packages:
  gfortran-doc gfortran-6-doc libgfortran3-dbg libcoarrays-dev libblas-doc
  liblapack-doc liblapack-dev libdigest-hmac-perl libgssapi-perl
  liblapack-doc-man libdata-dump-perl libcrypt-ssleay-perl libauthen-ntlm-perl
The following NEW packages will be installed:
  gfortran gfortran-6 libatlas-base-dev libatlas-dev libatlas3-base
  libaudio-scrobbler-perl libauthen-sasl-perl libblas-dev
  libconfig-inifiles-perl libencode-locale-perl libfile-listing-perl
  libfont-afm-perl libgfortran-6-dev libhtml-form-perl libhtml-format-perl
  libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl
  libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl
  libhttp-message-perl libhttp-negotiate-perl libio-html-perl
  libio-socket-ssl-perl liblwp-mediatypes-perl liblwp-protocol-https-perl
  libmagic-dev libmailtools-perl libnet-http-perl libnet-smtp-ssl-perl
  libnet-ssleay-perl libtimedate-perl liburi-perl libwww-perl
  libwww-robotrules-perl mpg321 perl-openssl-defaults
0 upgraded, 38 newly installed, 0 to remove and 0 not upgraded.
Need to get 12,1 MB of archives.
After this operation, 53,8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libgfortran-6-dev armhf 6.3.0-18+rpi1+deb9u1 [199 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian stretch/main armhf gfortran armhf 4:6.3.0-4 [1.352 B]
Get:2 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf gfortran-6 armhf 6.3.0-18+rpi1+deb9u1 [5.421 kB]
Get:4 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libatlas3-base armhf 3.10.3-1+rpi1 [1.920 kB]
Get:5 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libblas-dev armhf 3.7.0-2 [114 kB]
Get:6 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libatlas-dev armhf 3.10.3-1+rpi1 [65,9 kB]
Get:7 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libatlas-base-dev armhf 3.10.3-1+rpi1 [2.528 kB]
Get:8 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libconfig-inifiles-perl all 2.94-1 [53,4 kB]
Get:9 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libencode-locale-perl all 1.05-1 [13,7 kB]
Get:10 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libtimedate-perl all 2.3000-2+deb9u1 [37,9 kB]
Get:11 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhttp-date-perl all 6.02-1 [10,7 kB]
Get:12 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libfile-listing-perl all 6.04-1 [10,3 kB]
Get:13 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhtml-tagset-perl all 3.20-3 [12,7 kB]
Get:14 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf liburi-perl all 1.71-1 [88,6 kB]
Get:15 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhtml-parser-perl armhf 3.72-3 [101 kB]
Get:16 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhtml-tree-perl all 5.03-2 [210 kB]
Get:17 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libio-html-perl all 1.001-1 [17,6 kB]
Get:18 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf liblwp-mediatypes-perl all 6.02-1 [22,1 kB]
Get:19 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhttp-message-perl all 6.11-1 [75,9 kB]
Get:20 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhttp-cookies-perl all 6.01-1 [17,4 kB]
Get:21 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhttp-negotiate-perl all 6.00-2 [13,6 kB]
Get:22 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf perl-openssl-defaults armhf 3 [6.782 B]
Get:23 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libnet-ssleay-perl armhf 1.80-1 [270 kB]
Get:24 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libio-socket-ssl-perl all 2.044-1 [195 kB]
Get:25 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libnet-http-perl all 6.12-1 [23,8 kB]
Get:26 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf liblwp-protocol-https-perl all 6.06-2 [9.582 B]
Get:27 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libwww-robotrules-perl all 6.01-1 [14,3 kB]
Get:28 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libwww-perl all 6.15-1 [195 kB]
Get:29 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libaudio-scrobbler-perl all 0.01-2.3 [13,8 kB]
Get:30 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libauthen-sasl-perl all 2.1600-1 [50,8 kB]
Get:31 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libfont-afm-perl all 1.20-2 [13,6 kB]
Get:32 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhtml-form-perl all 6.03-1 [23,9 kB]
Get:33 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhtml-format-perl all 2.12-1 [43,5 kB]
Get:34 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libhttp-daemon-perl all 6.01-1 [17,3 kB]
Get:35 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libmagic-dev armhf 1:5.30-1+deb9u3 [115 kB]
Get:36 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libnet-smtp-ssl-perl all 1.04-1 [6.184 B]
Get:37 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf libmailtools-perl all 2.18-1 [88,5 kB]
Get:38 http://mirror.rise.ph/raspbian/raspbian stretch/main armhf mpg321 armhf 0.3.2-1.1 [55,2 kB]
Fetched 12,1 MB in 24s (495 kB/s)                                              
Ekstrak template dari paket: 100%
Selecting previously unselected package libgfortran-6-dev:armhf.
(Sedang membaca basis data ...  113311 berkas atau direktori telah terpasang.)
Preparing to unpack .../00-libgfortran-6-dev_6.3.0-18+rpi1+deb9u1_armhf.deb ...
Unpacking libgfortran-6-dev:armhf (6.3.0-18+rpi1+deb9u1) ...
Selecting previously unselected package gfortran-6.
Preparing to unpack .../01-gfortran-6_6.3.0-18+rpi1+deb9u1_armhf.deb ...
Unpacking gfortran-6 (6.3.0-18+rpi1+deb9u1) ...
Selecting previously unselected package gfortran.
Preparing to unpack .../02-gfortran_4%3a6.3.0-4_armhf.deb ...
Unpacking gfortran (4:6.3.0-4) ...
Selecting previously unselected package libatlas3-base.
Preparing to unpack .../03-libatlas3-base_3.10.3-1+rpi1_armhf.deb ...
Unpacking libatlas3-base (3.10.3-1+rpi1) ...
Selecting previously unselected package libblas-dev.
Preparing to unpack .../04-libblas-dev_3.7.0-2_armhf.deb ...
Unpacking libblas-dev (3.7.0-2) ...
Selecting previously unselected package libatlas-dev.
Preparing to unpack .../05-libatlas-dev_3.10.3-1+rpi1_armhf.deb ...
Unpacking libatlas-dev (3.10.3-1+rpi1) ...
Selecting previously unselected package libatlas-base-dev.
Preparing to unpack .../06-libatlas-base-dev_3.10.3-1+rpi1_armhf.deb ...
Unpacking libatlas-base-dev (3.10.3-1+rpi1) ...
Selecting previously unselected package libconfig-inifiles-perl.
Preparing to unpack .../07-libconfig-inifiles-perl_2.94-1_all.deb ...
Unpacking libconfig-inifiles-perl (2.94-1) ...
Selecting previously unselected package libencode-locale-perl.
Preparing to unpack .../08-libencode-locale-perl_1.05-1_all.deb ...
Unpacking libencode-locale-perl (1.05-1) ...
Selecting previously unselected package libtimedate-perl.
Preparing to unpack .../09-libtimedate-perl_2.3000-2+deb9u1_all.deb ...
Unpacking libtimedate-perl (2.3000-2+deb9u1) ...
Selecting previously unselected package libhttp-date-perl.
Preparing to unpack .../10-libhttp-date-perl_6.02-1_all.deb ...
Unpacking libhttp-date-perl (6.02-1) ...
Selecting previously unselected package libfile-listing-perl.
Preparing to unpack .../11-libfile-listing-perl_6.04-1_all.deb ...
Unpacking libfile-listing-perl (6.04-1) ...
Selecting previously unselected package libhtml-tagset-perl.
Preparing to unpack .../12-libhtml-tagset-perl_3.20-3_all.deb ...
Unpacking libhtml-tagset-perl (3.20-3) ...
Selecting previously unselected package liburi-perl.
Preparing to unpack .../13-liburi-perl_1.71-1_all.deb ...
Unpacking liburi-perl (1.71-1) ...
Selecting previously unselected package libhtml-parser-perl.
Preparing to unpack .../14-libhtml-parser-perl_3.72-3_armhf.deb ...
Unpacking libhtml-parser-perl (3.72-3) ...
Selecting previously unselected package libhtml-tree-perl.
Preparing to unpack .../15-libhtml-tree-perl_5.03-2_all.deb ...
Unpacking libhtml-tree-perl (5.03-2) ...
Selecting previously unselected package libio-html-perl.
Preparing to unpack .../16-libio-html-perl_1.001-1_all.deb ...
Unpacking libio-html-perl (1.001-1) ...
Selecting previously unselected package liblwp-mediatypes-perl.
Preparing to unpack .../17-liblwp-mediatypes-perl_6.02-1_all.deb ...
Unpacking liblwp-mediatypes-perl (6.02-1) ...
Selecting previously unselected package libhttp-message-perl.
Preparing to unpack .../18-libhttp-message-perl_6.11-1_all.deb ...
Unpacking libhttp-message-perl (6.11-1) ...
Selecting previously unselected package libhttp-cookies-perl.
Preparing to unpack .../19-libhttp-cookies-perl_6.01-1_all.deb ...
Unpacking libhttp-cookies-perl (6.01-1) ...
Selecting previously unselected package libhttp-negotiate-perl.
Preparing to unpack .../20-libhttp-negotiate-perl_6.00-2_all.deb ...
Unpacking libhttp-negotiate-perl (6.00-2) ...
Selecting previously unselected package perl-openssl-defaults:armhf.
Preparing to unpack .../21-perl-openssl-defaults_3_armhf.deb ...
Unpacking perl-openssl-defaults:armhf (3) ...
Selecting previously unselected package libnet-ssleay-perl.
Preparing to unpack .../22-libnet-ssleay-perl_1.80-1_armhf.deb ...
Unpacking libnet-ssleay-perl (1.80-1) ...
Selecting previously unselected package libio-socket-ssl-perl.
Preparing to unpack .../23-libio-socket-ssl-perl_2.044-1_all.deb ...
Unpacking libio-socket-ssl-perl (2.044-1) ...
Selecting previously unselected package libnet-http-perl.
Preparing to unpack .../24-libnet-http-perl_6.12-1_all.deb ...
Unpacking libnet-http-perl (6.12-1) ...
Selecting previously unselected package liblwp-protocol-https-perl.
Preparing to unpack .../25-liblwp-protocol-https-perl_6.06-2_all.deb ...
Unpacking liblwp-protocol-https-perl (6.06-2) ...
Selecting previously unselected package libwww-robotrules-perl.
Preparing to unpack .../26-libwww-robotrules-perl_6.01-1_all.deb ...
Unpacking libwww-robotrules-perl (6.01-1) ...
Selecting previously unselected package libwww-perl.
Preparing to unpack .../27-libwww-perl_6.15-1_all.deb ...
Unpacking libwww-perl (6.15-1) ...
Selecting previously unselected package libaudio-scrobbler-perl.
Preparing to unpack .../28-libaudio-scrobbler-perl_0.01-2.3_all.deb ...
Unpacking libaudio-scrobbler-perl (0.01-2.3) ...
Selecting previously unselected package libauthen-sasl-perl.
Preparing to unpack .../29-libauthen-sasl-perl_2.1600-1_all.deb ...
Unpacking libauthen-sasl-perl (2.1600-1) ...
Selecting previously unselected package libfont-afm-perl.
Preparing to unpack .../30-libfont-afm-perl_1.20-2_all.deb ...
Unpacking libfont-afm-perl (1.20-2) ...
Selecting previously unselected package libhtml-form-perl.
Preparing to unpack .../31-libhtml-form-perl_6.03-1_all.deb ...
Unpacking libhtml-form-perl (6.03-1) ...
Selecting previously unselected package libhtml-format-perl.
Preparing to unpack .../32-libhtml-format-perl_2.12-1_all.deb ...
Unpacking libhtml-format-perl (2.12-1) ...
Selecting previously unselected package libhttp-daemon-perl.
Preparing to unpack .../33-libhttp-daemon-perl_6.01-1_all.deb ...
Unpacking libhttp-daemon-perl (6.01-1) ...
Selecting previously unselected package libmagic-dev:armhf.
Preparing to unpack .../34-libmagic-dev_1%3a5.30-1+deb9u3_armhf.deb ...
Unpacking libmagic-dev:armhf (1:5.30-1+deb9u3) ...
Selecting previously unselected package libnet-smtp-ssl-perl.
Preparing to unpack .../35-libnet-smtp-ssl-perl_1.04-1_all.deb ...
Unpacking libnet-smtp-ssl-perl (1.04-1) ...
Selecting previously unselected package libmailtools-perl.
Preparing to unpack .../36-libmailtools-perl_2.18-1_all.deb ...
Unpacking libmailtools-perl (2.18-1) ...
Selecting previously unselected package mpg321.
Preparing to unpack .../37-mpg321_0.3.2-1.1_armhf.deb ...
Unpacking mpg321 (0.3.2-1.1) ...
Sedang menata libhtml-tagset-perl (3.20-3) ... 
Sedang menata libatlas3-base (3.10.3-1+rpi1) ... 
update-alternatives: using /usr/lib/atlas-base/atlas/libblas.so.3 to provide /usr/lib/libblas.so.3 (libblas.so.3) in auto mode
update-alternatives: using /usr/lib/atlas-base/atlas/liblapack.so.3 to provide /usr/lib/liblapack.so.3 (liblapack.so.3) in auto mode
Sedang menata libfont-afm-perl (1.20-2) ... 
Sedang menata libconfig-inifiles-perl (2.94-1) ... 
Sedang menata libencode-locale-perl (1.05-1) ... 
Sedang menata libmagic-dev:armhf (1:5.30-1+deb9u3) ... 
Sedang menata libtimedate-perl (2.3000-2+deb9u1) ... 
Sedang menata perl-openssl-defaults:armhf (3) ... 
Sedang menata libio-html-perl (1.001-1) ... 
Sedang menata libgfortran-6-dev:armhf (6.3.0-18+rpi1+deb9u1) ... 
Sedang menata liblwp-mediatypes-perl (6.02-1) ... 
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Sedang menata liburi-perl (1.71-1) ... 
Sedang menata mpg321 (0.3.2-1.1) ... 
Sedang menata libhtml-parser-perl (3.72-3) ... 
Processing triggers for man-db (2.7.6.1-2) ...
Sedang menata libnet-http-perl (6.12-1) ... 
Sedang menata libwww-robotrules-perl (6.01-1) ... 
Sedang menata libauthen-sasl-perl (2.1600-1) ... 
Sedang menata gfortran-6 (6.3.0-18+rpi1+deb9u1) ... 
Sedang menata libhttp-date-perl (6.02-1) ... 
Sedang menata libnet-ssleay-perl (1.80-1) ... 
Sedang menata libio-socket-ssl-perl (2.044-1) ... 
Sedang menata libhtml-tree-perl (5.03-2) ... 
Sedang menata libfile-listing-perl (6.04-1) ... 
Sedang menata libhttp-message-perl (6.11-1) ... 
Sedang menata libhttp-negotiate-perl (6.00-2) ... 
Sedang menata gfortran (4:6.3.0-4) ... 
update-alternatives: using /usr/bin/gfortran to provide /usr/bin/f95 (f95) in auto mode
update-alternatives: using /usr/bin/gfortran to provide /usr/bin/f77 (f77) in auto mode
Sedang menata libnet-smtp-ssl-perl (1.04-1) ... 
Sedang menata libhtml-format-perl (2.12-1) ... 
Sedang menata libhttp-cookies-perl (6.01-1) ... 
Sedang menata libblas-dev (3.7.0-2) ... 
update-alternatives: using /usr/lib/libblas/libblas.so to provide /usr/lib/libblas.so (libblas.so) in auto mode
Sedang menata libhttp-daemon-perl (6.01-1) ... 
Sedang menata libhtml-form-perl (6.03-1) ... 
Sedang menata libatlas-dev (3.10.3-1+rpi1) ... 
Sedang menata libmailtools-perl (2.18-1) ... 
Sedang menata libatlas-base-dev (3.10.3-1+rpi1) ... 
update-alternatives: using /usr/lib/atlas-base/atlas/libblas.so to provide /usr/lib/libblas.so (libblas.so) in auto mode
update-alternatives: using /usr/lib/atlas-base/atlas/liblapack.so to provide /usr/lib/liblapack.so (liblapack.so) in auto mode
Sedang menata libwww-perl (6.15-1) ... 
Sedang menata liblwp-protocol-https-perl (6.06-2) ... 
Sedang menata libaudio-scrobbler-perl (0.01-2.3) ... 
pi@raspberrypi:~ $ cd ~/MagicMirror/modules/
pi@raspberrypi:~/MagicMirror/modules $ git clone https://github.com/eouia/MMM-Hotword.git
Cloning into 'MMM-Hotword'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 447 (delta 10), reused 13 (delta 4), pack-reused 419
Receiving objects: 100% (447/447), 8.09 MiB | 2.12 MiB/s, done.
Resolving deltas: 100% (258/258), done.
pi@raspberrypi:~/MagicMirror/modules $ cd MMM-Hotword
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ chmod +x ./installer/install.sh
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ ./installer/install.sh
Cloning into 'snowboy'...
remote: Enumerating objects: 2145, done.
remote: Total 2145 (delta 0), reused 0 (delta 0), pack-reused 2145
Receiving objects: 100% (2145/2145), 55.22 MiB | 2.55 MiB/s, done.
Resolving deltas: 100% (1072/1072), done.
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm notice created a lockfile as package-lock.json. You should commit this file.
+ nan@2.14.0
+ node-pre-gyp@0.6.39
added 115 packages from 85 contributors and audited 269 packages in 19.951s

1 package is looking for funding
  run `npm fund` for details

found 10 vulnerabilities (8 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.19.0 | linux | arm
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.19.0 | linux | arm
gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.19.0/node-v10.19.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.19.0/node-v10.19.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.19.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.19.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/10.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/10.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/10.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-Hotword/snowboy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.19.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Memasuki direktori '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
  COPY Release/snowboy.node
  COPY /home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Meninggalkan direktori '/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/build'
gyp info ok 
node-pre-gyp info ok 

> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> snowboy@1.3.1 prepublish /home/pi/MagicMirror/modules/MMM-Hotword/snowboy
> tsc --listFiles

../../../node_modules/@types/unist/index.d.ts:31:20 - error TS2304: Cannot find name 'unknown'.

31     [key: string]: unknown;
                      ~~~~~~~


../../../node_modules/@types/unist/index.d.ts:40:20 - error TS2304: Cannot find name 'unknown'.

40     [key: string]: unknown;
                      ~~~~~~~

../../../node_modules/@types/unist/index.d.ts:97:12 - error TS2304: Cannot find name 'unknown'.

97     value: unknown;
              ~~~~~~~


../../../node_modules/@types/vfile/index.d.ts:48:15 - error TS2304: Cannot find name 'unknown'.

48         data: unknown;
                 ~~~~~~~

../../../node_modules/vfile-message/types/index.d.ts:67:20 - error TS2304: Cannot find name 'unknown'.

67     [key: string]: unknown
                      ~~~~~~~


/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/typescript/lib/lib.es6.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/index.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/node-pre-gyp.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/lib/node/SnowboyDetectNative.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/@types/node/base.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/snowboy/node_modules/@types/node/index.d.ts
/home/pi/MagicMirror/node_modules/@types/color-name/index.d.ts
/home/pi/MagicMirror/node_modules/@types/minimist/index.d.ts
/home/pi/MagicMirror/node_modules/@types/normalize-package-data/index.d.ts
/home/pi/MagicMirror/node_modules/@types/parse-json/index.d.ts
/home/pi/MagicMirror/node_modules/@types/unist/index.d.ts
/home/pi/MagicMirror/node_modules/vfile-message/types/index.d.ts
/home/pi/MagicMirror/node_modules/@types/vfile/index.d.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! snowboy@1.3.1 prepublish: `tsc --listFiles`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-02-25T15_37_09_743Z-debug.log
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
+ electron-rebuild@1.10.0
added 90 packages from 76 contributors, removed 15 packages and audited 512 packages in 28.074s

2 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (8 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
✔ Rebuild Complete
electron-v3.1-linux-arm  node-v64-linux-arm
lib/node/index.js

**Comment by nenengherlina** [comment]
I already run 'npm audit fix' and 'npm audit' and this is the result

pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ npm audit fix
npm ERR! code EAUDITNOLOCK
npm ERR! audit Neither npm-shrinkwrap.json nor package-lock.json found: Cannot audit a project without a lockfile
npm ERR! audit Try creating one first with: npm i --package-lock-only

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-02-25T16_08_17_653Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ npm audit
npm ERR! code EAUDITNOLOCK
npm ERR! audit Neither npm-shrinkwrap.json nor package-lock.json found: Cannot audit a project without a lockfile
npm ERR! audit Try creating one first with: npm i --package-lock-only

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-02-25T16_09_47_988Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $

**Comment by eouia** [comment]
> ✔ Rebuild Complete
electron-v3.1-linux-arm node-v64-linux-arm
lib/node/index.js

This means finally rebuild was completed regards of previous errors or warnings or whatever.

**Comment by bugsounet** [comment]
hi,  wiki says  [this](https://github.com/eouia/MMM-Hotword/wiki/Installation#auto-install)

**Comment by bugsounet** [comment]
*supposed solved reopen issue if needed*
