### ISSUE TITLE
Voice detection issue

### ISSUE THREAD

**Issue by MajestyBilly** [bugsounet/MMM-Hotword#132]
Hello,
So, I've set up my MMM-Hotword to my MMM-AssistantMk2, and it's working.... ish.

It literally only works if I'm like 5cm from the mic and really articulate the word "computer", and even if I do that, it only works like 1/20 times? Any ideas?

config:
`mic: {
   recordProgram: "arecord",
   device: "plughw:1",
  }`

and

` models: [
      {
        hotwords    : "computer",
        file        : "computer.umdl",
        sensitivity : "0.5",
      },`

**Comment by eouia** [comment]
First try mic volume up.
And per your environment, and vocal pattern, adjust sensitivity. But which value would match i can’t sure. Find your values.

**Comment by MajestyBilly** [comment]
> First try mic volume up.
> And per your environment, and vocal pattern, adjust sensitivity. But which value would match i can’t sure. Find your values.

Mic volume is at 100%. What is the sensitivity "range" btw? Is it 0.0-2.0? Should I crank it up to 2.0?

**Comment by eouia** [comment]
To 1.0, but could not confirm higher or lower which would be better in your case. Many trials will be needed.

**Comment by bugsounet** [comment]
closing issue, we think it's solved
