### ISSUE TITLE
MMM-Hotword detects hotword but doesn't activate MMM-AssistantMk2 after recent update.

### ISSUE THREAD

**Issue by yurMoThEr** [bugsounet/MMM-Hotword#139]
After I say the hotword, the MMM-Hotword logo changes, but nothing happens. Here's my config file for MMM-AssistantMk2 and MMM-Hotword:
{
		  module: "MMM-AssistantMk2",
		  position: "fullscreen_above",
		  config: {
		    ui: "Fullscreen",
		    assistantConfig: {
		      latitude: 43.772099,
		      longitude: -79.344490,
		    },
		    micConfig: { // put there configuration generated by auto-installer
		      recorder: "arecord",
		      device: "plughw:1",
		    },
		    recipes: [ "with-MMM-Hotword.js", "with-MMM-Youtube.js" ],
		    profiles: {
		      "default": {
			profileFile: "default.json",
			lang: "en-US"
		      }
		    },
		    useA2D: false,
		  }
		},
		{
		  module: "MMM-Hotword",
		  position: "top_right",
		  config: {
		    chimeOnFinish: null,
		    mic: {
		      recordProgram: "arecord",
		      device: "plughw:1"
		    },
		    models: [
		      {
			hotwords    : "smart_mirror",
			file        : "smart_mirror.umdl",
			sensitivity : "0.5",
		      },
		    ],
		    commands: {
		      "computer": {
			notificationExec: {
			  notification: "TEST",
			},
			restart:false,
			afterRecordLimit:0
		      }
		    }
		  }
		},

**Comment by bugsounet** [comment]
hi, your hotword configuration is not configured correctly for AMk2
I think it's not after the recent update .... but since the begin

For me it's not an issue sorry
please read wiki page of hotword and Amk2 correctly and retry
