### ISSUE TITLE
Hotword.

### ISSUE THREAD

**Issue by Alan-Lan2** [bugsounet/MMM-Hotword#143]
Hi.  Perform the magic mirror installation correctly, but I want to get a personal model (.pmdl) and my question is about the installation, I have read the guide but I do not know where to get data.json and volume.pmdl.  Also about step 3, where did you make the recording?  , in the rpi console?.
I would appreciate it if you could help me.

**Comment by bugsounet** [comment]
yes, you should use the console of your RPI
it will use the mic of your RPI for create your own model
