### ISSUE TITLE
keeps listening

### ISSUE THREAD

**Issue by jhoyos135** [bugsounet/MMM-Hotword#146]
hey there,
I'm trigger an alert when I say a hotword but the problem is that the alert keep popping up with any other word, other than the hotword, this are my last logs, not sure why this is happening. it just keeps firing the detected notification
```
[2020-05-09 20:08:39.985] [LOG]    [HOTWORD] begins.
[2020-05-09 20:08:39.997] [LOG]    [HOTWORD] Detector starts listening.
[2020-05-09 20:08:41.337] [LOG]    [HOTWORD] Detected: computer
[2020-05-09 20:08:41.355] [LOG]    [HOTWORD] stops.
[2020-05-09 20:08:41.376] [LOG]    [HOTWORD] Final Result: { detected: true, hotword: 'computer', file: null }
[2020-05-09 20:08:42.510] [LOG]    [HOTWORD] begins.
[2020-05-09 20:08:42.519] [LOG]    [HOTWORD] Detector starts listening.
```
Is pretty much triggering any word in any conversation without even saying the trigger word
this is my configuration 
```
{
    module: "MMM-Hotword",
    position: "bottom_right",
    config: {
        useDisplay: true,
        pauseOnYoutube: false,
        recipes: [],
        mic: {
            recordProgram: "arecord",
            device: "plughw:1",

        },


        models: [{
            hotwords: "computer",
            file: "computer.umdl",
            sensitivity: 0.8,
        }, ],

        commands: {
            "computer": {
                notificationExec: {
                    notification: () => {
                        return "SHOW_ALERT"
                    },
                    payload: (hotword, file) => {
                        return {
                            message: 'test',
                            timer: 2600
                        }
                    }
                },
                restart: true
            },
        }

    }
},
```

**Comment by bugsounet** [comment]
hi, i think the sensitivity is too high and syntax is not correct

try to replace
```
sensitivity: 0.8,
```
by the default sensitivity
```
sensitivity: " 0.6",
```

note for sensitivity:
Value could be within a range from "0.0" to "1.0".
"0.0" : low detect
"1.0": high detect
it's depend again to your microphone volume (alsamixer)

**Comment by jhoyos135** [comment]
I think the sensitivity has to do with how easy the mic picks up the sound, not the keyword, it I lower it, it doesn't even hear me.

**Comment by jhoyos135** [comment]
actually nvm, but still an issue, I did the normal setup with AssistantMk2 with all default configurations and it triggers with any sound available.

**Comment by bugsounet** [comment]
Archived Modules
