### ISSUE TITLE
Unable to create .pmdl

### ISSUE THREAD

**Issue by sanjeyk** [bugsounet/MMM-Hotword#148]
The following command doesn't work.
rec -r 16000 -c 1 -b 16 -e signed-integer 1.wav
rec -r 16000 -c 1 -b 16 -e signed-integer 2.wav
rec -r 16000 -c 1 -b 16 -e signed-integer 3.wav

Can you please help me to resolve this issue?

**Comment by bugsounet** [comment]
Archived Modules
