### ISSUE TITLE
안녕하세요 깃허브보면서 매직미러를 만들고있는대 문제가 생겨서 질문 남깁니다

### ISSUE THREAD

**Issue by tjtmddn** [bugsounet/MMM-Hotword#81]
다른 명령어는 말할 때는 화면에 아이콘이 깜빡이기만 하고 computer라고 명령을 말하면 화면에 computer라고 글씨가 표시는 되기는 하지만 글씨가 뜬채로 google assistant api가 작동하지 않습니다. (토큰등 중요한 내용들은 첨부하지않았습니다!)

도움을 구해봅니다..

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
No helper found for module: MMM-AssistantMk2.
Initializing new module helper ...
Module helper loaded: MMM-Hotword
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: MMM-AQI
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AQI
MMM-AQI helper started ...
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics - Interval: 3600000
Create new news fetcher for url: https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=03&plink=RSSREADER - Interval: 300000
Create new news fetcher for url: https://world.kbs.co.kr/rss/rss_news.htm?lang=k - Interval: 300000
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: smartmirror
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'smartmirror', file: null }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed
Stopping module helper: MMM-Hotword
Stopping module helper: MMM-AQI

magic mirror  명령어를 말하고 종료시에는 이런식으로 나옵니다 
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: smartmirror
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'smartmirror', file: null }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed
Stopping module helper: MMM-Hotword
Stopping module helper: MMM-AQI

config.js

var config = {
  address: "localhost",
  port: 8080,
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],
  language: "ko",
  timeFormat: 12,
  units: "metric",

  modules: [
    {
      module: "alert",
    },
    {
      module: "updatenotification",  
      position: "top_bar" 
    },
    {
      module: "clock",  
      position: "top_left", 
      config: {
        dateFormat: "LL dddd",
      }
    },
    {
      module: "calendar",
      position: "top_left",
      config: {
        urgency: 21,
        fetchInterval: 3600000,
        calendars: [{
          url: 'https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics',
          symbol: '대한민국 공휴일',
        }, ]
      }
    },
    {
      module: "currentweather", 
      position: "top_right",
      config: {
        location: "", 
        locationID: "",
        appid: ""
      }
    },
    {
      module: "weatherforecast", 
      position: "top_right", 
      header: "Weather Forecast",
      config: {
        location: "", /
        locationID: "",
        appid: "api key 
      }
    },
    {
      module: "newsfeed",
      position: "bottom_bar", 
      config: {
        feeds: [
                {
                  title: "SBS 뉴스",
                  url: "https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=03&plink=RSSREADER",
                },
                {
                  title: "KBS 뉴스",
                  url: "https://world.kbs.co.kr/rss/rss_news.htm?lang=k"
                }
               ]
      }
    },
{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    useWelcomeMessage: "brief today"
  }
},
    {
  module: "MMM-Hotword",
  position: "top_right",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1"
    },
    models: [
      {
        hotwords    : "computer",
        file        : "computer.umdl",
        sensitivity : "0.5",
      },
    {
     hotwords: ["jarvis", "jarvis"],
     file: "jarvis.umdl",
     sensitivity: "0.8,0.8",
   },
{
     hotwords: "hey_extreme",
     file: "hey_extreme.umdl",
     sensitivity: "0.6",
   },
{
     hotwords: "view_glass",
     file: "view_glass.umdl",
     sensitivity: "0.7",
   },
{
     hotwords: "smartmirror",
     file: "smart_mirror.umdl",
     sensitivity: '1.0',
   },
    ],
    commands: {
      "computer": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    }
  }
},
    {
      module: "compliments",  
      position: "middle_center", 
      config: {
        compliments: {
          anytime: [ //아무 때나
            "오늘도 좋은 하루!"
          ],
          morning: [ //아침
            "좋은 아침!",
            "힘찬 아침!",
            "잘 잤나요?"
          ],
          afternoon: [ //오후
            "안녕하세요!",
            "멋져요!",
            "잘 지내고 있나요!"
          ],
          evening: [ //저녁
            "밤이 왔어요",
            "편안한 밤",
            "반가워요!"
          ],
          day_sunny: [//맑은 낮
            "하늘이 맑아요."
          ],
          day_cloudy: [//흐린 낮
           
          ],
          cloudy: [//흐림
            "흐린 날이네요."
          ],
          cloudy_windy: [//흐리고 바람
            "바람이 조금 불어요."
          ],
          showers: [//소나기
            "갑자기 비가 와요."
          ],
          rain: [//비
            "우산 챙기세요!"
          ],
          thunderstorm: [//천둥번개
            "번개가 무서워요!"
          ],
          snow: [//눈
            "하늘에서 눈이 내려와요~"
          ],
          fog: [//안개
            "안개가 자욱해요."
          ],
          night_clear: [//맑은 밤
            "오늘 밤은 하늘이 맑아요."
          ],
          night_cloudy: [//흐린 밤
            "별이 잘 안 보여요."
          ],
          night_showers: [//소나기 밤

          ],
          night_rain: [//비오는 밤
            "창문 닫고 자요."
          ],
          night_thunderstorm: [//천둥번개 밤
            "오늘 밤은 시끄럽겠어요."
          ],
          night_snow: [//눈오는 밤
            "아침에 눈이 쌓여 있을까요?"
          ],
          night_alt_cloudy_windy: [//흐리고 바람부는 밤

          ],
        }
      }
    },

{
 module: 'MMM-AQI',  
 position: 'bottom_right',  
 header: 'Air Quality Index (AQI)',
 config: {
  token: ", 
  city: "@11493", 
  iaqi: true,
  updateInterval: 10 * 60 * 1000,
  initialLoadDelay: 0,
  animationSpeed: 1000,
  debug: false
 }
    }

    
  ]
};

/*************** DO NOT EDIT THE LINE BELOW 아래는 편집하지 마십시오. ***************/
if (typeof module !== "undefined") {
  module.exports = config;
}

**Comment by eouia** [comment]
일단 로그가 완전하지 않아서 주신 로그만 가지고는 뭘 알기 어렵네요.
1) 현재 config.js를 백업해두시고, 새로 MMM-Hotword와 MMM-AssistantMk2만 넣은 config으로 테스트해보세요.
2) MMM-AssitantMk2 config이 저거 뿐인가요? 뭔가 많이 부족하네요.
3) MMM-Hotword에서 굳이 사용안할 핫워드들을 등록해두실 필요는 없을텐데요. 그리고 실제로 실행될 command로는 "computer"만 등록해두셨네요.

config관련해서는 
https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration#with-mmm-hotwordv2
일단 여기서부터 시작해보세요.

**Comment by tjtmddn** [comment]
위에 문제는 동영상 보면서 해결해서 음성인식 까지는 했습니다 혹시 스마트미러에 지도를 넣고 싶은대 모듈을 깔아야하는지 config만 수정해서도 지도를 띄울수 있는지 궁금합니다!

**Comment by eouia** [comment]
지도가 어떤 지도인지 모르겠네요. 기본적으로는 없습니다만 경로 탐색을 요청한 경우 작은 지도가 나오긴 합니다. 자바스크립트를 잘 아신다면 원하시는 기능이 가능하도록 모듈을 만드실 수 있습니다. 그리 어렵지는 않지만, 기본 지식은 있어야겠죠
다음 버전에서는 경로 탐색시 구글 맵을 풀스크린으로 띄우는 기능을 추가할 예정이긴 합니다.

**Comment by tjtmddn** [comment]
알려주신 방법대로 진행중이여서 지도 빼고는 거의다 해결을 한거같습니다. 혹시 유튜브 음성인식으로 멈추고 다시시작하고 스마트미러창으로 다시 돌아오고 싶은대 혹시 다른모듈을 설치해야하는지 아님 파일 수정만으로도 해결되는지 궁금합니다.

**Comment by eouia** [comment]
`pauseOnYoutube: false` 로 세팅하시면 유튜브 재생중에도 핫워드 인식대기 상태가 됩니다. 핫워드를 말해서 Assistant가 액티베이팅되면 자동으로 현재 재생하고 있는 화면을 중지/숨기게 됩니다.
다만.. 이렇게 하면 마이크가 계속 열려 있는 상태가 되기 때문에 오작동할 가능성이 커서 별로 권하지 않습니다.

애초에, 유튜브 영상 연결하는 기능을 만들어넣은 것 자체가 괜한 짓이라는 생각이라 다음 버전에서는 삭제될 예정입니다.

**Comment by tjtmddn** [comment]
1.올려주신 모듈을 이용해서 screen_off/on기능을 적용했습니다 그런대 off는 작동하는대 on은 인식을 하지않습니다 hide all 은 아예 작동을 하지않았구요 혹시 이것에 대한 해결 방한을 알려주실수 있으신가요? 
2.구글 어시스턴트를 이용한 음성인식 지도 컨트롤에 가능여부를 알고싶습니다 가능하다면 구체적으로 방법을 알 수 있을까요? 죄송합니다 자바스크립트가 미숙해서 이렇게 질문을 자주하네요 항상 도움주셔서 감사합니다!

**Comment by eouia** [comment]
그냥 동작하지 않는다고 하셔도 저는 원인을 알 수 없습니다. 일단 config.js와 사용하신 레시피와 에러로그 파일을 전부 보지 않는 한은 뭐가 문제인지 알 수 없네요.

두번째 질문에 대해서는;
- 일단, 지도 모듈이 있으신가요? 직접 만드셨든, 다른 이가 만들었든
- 그리고 해당 모듈이 controllable해야 합니다. notification이든 아니면 내부 메쏘드이든. 해당 모듈이 어떤 형태로든 외부 다른 모듈로부터의 제어를 받아 들일 수 있어야만 컨트롤을 하든 말든 하겠죠.
- 일단 그렇게 되어 있다는 전제하에;
크게 3가지 제어 방식이 있습니다.

1) 특정 패턴에 대해 IFTTT에 **THIS**로 등록하고, **THAT**으로 Webhook을 선택해서 MagicMirror를 가리키게 하는 법. 
물론 webhook 결과로 돌아오는 신호에 대해 실제로 뭘 해야 할지는 추가해줘야 겠지요. 쉽기는 제일 쉬운데, 복잡한 형태는 다루기 힘들고, 무엇보다 public & static IP/Domain이 가능해야 합니다. (ngrok이나 dataplicity 등으로 할 수 있스니다.)

2) 특정 패턴에 대해 transcriptionHook으로 등록해두고, 해당 패턴이 인식되었을 때 Assistant의 응답을 가로채고 내가 지정한 명령이 실행되도록 하는 법.
다만, 이건 자연스러운 Assistant의 실행을 강제로 가로채는 거라 부작용이 있을 수 있어 가로챌 패턴 정의를 주의해야 합니다.

3) custom gAction을 만들어 Assistant 서버에 등록, 해당하는 패턴이 인식되면 아예 Assistant의 정상 응답으로 돌려받아 내가 지정한 명령이 실행되도록 하는 법
이게 제일 좋은 방법인데, 좀 복잡하긴 합니다.

https://github.com/eouia/MMM-AssistantMk2/wiki/Usage
를 참조하시면 됩니다. 아까 언급한 지도모듈이 있다면 이런 형태로 제어할 수 있습니다.

**Comment by bugsounet** [comment]
closing: Old version of MM / AMk2
