### ISSUE TITLE
음성인식이 자동으로 실행되기 위해서는 어떤 과정이 필요한가요??

### ISSUE THREAD

**Issue by LCH-511** [bugsounet/MMM-Hotword#91]
설치는 마무리하였는데, 음성인식이 마우스클릭 없이 자동으로 실행되려면 어떻게 해야하나요??

**Comment by eouia** [comment]
MMM-Hotword는 마우스클릭 같은 게 필요없는데, 아마 MMM-AssistantMk2 를 말하시는 것 같네요. github에 들어있는 문서를 읽고, MMM-Hotword와 함께 쓰기 위한 configuration을 설정해주세요.
