### ISSUE TITLE
GET http://localhost:8080/modules/MMM-Hotword/null 404 (Not Found) 

### ISSUE THREAD

**Issue by bao0720** [bugsounet/MMM-Hotword#96]
Excuse me

MMM-Hotword and MMM-AssistantMk2 is not unable to dialogue

in npm start dev

![2019-12-03-175154_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70040042-d0a70900-15f5-11ea-95f4-25cf74b78478.png)

The question is

GET http://localhost:8080/modules/MMM-Hotword/null 404 (Not Found)
temp.html:65 Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at new S (temp.html:65)
    at new Y (temp.html:69)
    at Function.Y.a (temp.html:69)
    at temp.html:72

Log

pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Started with text query: brief today
{ requestId: '5dec72c0-0000-2f14-9f68-f40304394fec' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5dec72c0-0000-2f14-9f68-f40304394fec' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed

config.js

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
	
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},

		{
	  module: "MMM-Hotword",
	  position: "top_right",
	  config: {
	    chimeOnFinish: null,
	    mic: {
	      recordProgram: "arecord",
	      device: "plughw:1"
	    },
	    models: [
	      {
		hotwords    : "computer",
		file        : "computer.umdl",
		sensitivity : "0.5",
	      },
	    ],
	    commands: {
	      "computer": {
		notificationExec: {
		  notification: "ASSISTANT_ACTIVATE",
		  payload: (detected, afterRecord) => {
		    return {profile:"default"}
		  }
		},
		restart:false,
		afterRecordLimit:0
	      }
	    }
	  }
	},
	{
		module: "MMM-AssistantMk2",
		position: "top_right",
		config: {
			deviceLocation: {
				coordinates: {
					latitude: 37.5650168, // -90.0 - +90.0
					longitude: 126.8491231, // -180.0 - +180.0
				},
			},
			record: {
				recordProgram : "arecord",  
				device        : "plughw:0",
			},
			notifications: {
				ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
				ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
			},
			useWelcomeMessage: "brief today",
			profiles: {
				"default" : {
					lang: "en-US"    //en-US
				}
			},
		}
	},

		]

	};

       /*************** DO NOT EDIT THE LINE BELOW ***************/
       if (typeof module !== "undefined") {module.exports = config;}

**Comment by bao0720** [comment]
/* Magic Mirror Config Sample
	 *
	 * By Michael Teeuw http://michaelteeuw.nl
	 * MIT Licensed.
	 *
	 * For more information how you can configurate this file
	 * See https://github.com/MichMich/MagicMirror#configuration
	 *
	 */

	var config = {
		address: "localhost", // Address to listen on, can be:
			              // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
			              // - another specific IPv4/6 to listen on a specific interface
			              // - "", "0.0.0.0", "::" to listen on any interface
			              // Default, when address config is left out, is "localhost"
		port: 8080,
		ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
			                                               // or add a specific IPv4 of 192.168.1.5 :
			                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
			                                               // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
			                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

		language: "en",
		timeFormat: 24,
		units: "metric",

		modules: [
			{
				module: "alert",
			},
			{
				module: "updatenotification",
				position: "top_bar"
			},
			{
				module: "clock",
				position: "top_left"
			},
			{
				module: "calendar",
				header: "US Holidays",
				position: "top_left",
				config: {
					calendars: [
						{
							symbol: "calendar-check",
							url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
					]
				}
			},
			{
				module: "compliments",
				position: "lower_third"
			},
		
			{
				module: "newsfeed",
				position: "bottom_bar",
				config: {
					feeds: [
						{
							title: "New York Times",
							url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
						}
					],
					showSourceTitle: true,
					showPublishDate: true,
					broadcastNewsFeeds: true,
					broadcastNewsUpdates: true
				}
			},


			{
		  module: "MMM-Hotword",
		  position: "top_right",
		  config: {
		    chimeOnFinish: null,
		    mic: {
		      recordProgram: "arecord",
		      device: "plughw:1"
		    },
		    models: [
		      {
			hotwords    : "computer",
			file        : "computer.umdl",
			sensitivity : "0.5",
		      },
		    ],
		    commands: {
		      "computer": {
			notificationExec: {
			  notification: "ASSISTANT_ACTIVATE",
			  payload: (detected, afterRecord) => {
			    return {profile:"default"}
			  }
			},
			restart:false,
			afterRecordLimit:0
		      }
		    }
		  }
		},
		{
			module: "MMM-AssistantMk2",
			position: "top_right",
			config: {
				deviceLocation: {
					coordinates: {
						latitude: 37.5650168, // -90.0 - +90.0
						longitude: 126.8491231, // -180.0 - +180.0
					},
				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
				useWelcomeMessage: "brief today",   //brief today
				profiles: {
					"default" : {
						lang: "en-US"    //en-US
					}

				},
			}
		},

			]

		};

		/*************** DO NOT EDIT THE LINE BELOW ***************/
		if (typeof module !== "undefined") {module.exports = config;}

**Comment by eouia** [comment]
I know that error message, but it would not do any harm to execution. So I don't think that error is the issue.
By the way, remove `useWelcomeMessage`. When you want to use that feature, more additional config is needed. At this moment, to make things simple, just remove it.

Then, try again.

**Comment by bao0720** [comment]
I delete useWelcomeMessage ,but not work

pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 14,
  metadata:
   Metadata { _internal_repr: { 'content-disposition': [Array] }, flags: 0 },
  details: 'Service unavailable.' }


config.js

/* Magic Mirror Config Sample
	 *
	 * By Michael Teeuw http://michaelteeuw.nl
	 * MIT Licensed.
	 *
	 * For more information how you can configurate this file
	 * See https://github.com/MichMich/MagicMirror#configuration
	 *
	 */

	var config = {
		address: "localhost", // Address to listen on, can be:
			              // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
			              // - another specific IPv4/6 to listen on a specific interface
			              // - "", "0.0.0.0", "::" to listen on any interface
			              // Default, when address config is left out, is "localhost"
		port: 8080,
		ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
			                                               // or add a specific IPv4 of 192.168.1.5 :
			                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
			                                               // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
			                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

		language: "en",
		timeFormat: 24,
		units: "metric",

		modules: [
			{
				module: "alert",
			},
			{
				module: "updatenotification",
				position: "top_bar"
			},
			{
				module: "clock",
				position: "top_left"
			},
			{
				module: "calendar",
				header: "US Holidays",
				position: "top_left",
				config: {
					calendars: [
						{
							symbol: "calendar-check",
							url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
					]
				}
			},
			{
				module: "compliments",
				position: "lower_third"
			},
		
			{
				module: "newsfeed",
				position: "bottom_bar",
				config: {
					feeds: [
						{
							title: "New York Times",
							url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
						}
					],
					showSourceTitle: true,
					showPublishDate: true,
					broadcastNewsFeeds: true,
					broadcastNewsUpdates: true
				}
			},

	{
	  module: "MMM-AssistantMk2",
	  position: "top_right",
	  config: {
	    record: {
	      recordProgram : "arecord",  
	      device        : "plughw:1",
	    },

	    notifications: {
	      ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
	      ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
	    },
	  }
	},
	{
	  module: "MMM-Hotword",
	  position: "top_right",
	  config: {
	    chimeOnFinish:null,
	    mic: {
	      recordProgram : "arecord",  
	      device        : "plughw:1",
	    },
	    models: [
	      {
		hotwords    : "smart_mirror",
		file        : "smart_mirror.umdl",
		sensitivity : "0.5",
	      },
	    ],
	    defaultCommand: {
	      notificationExec: {
		notification: "ASSISTANT_ACTIVATE",
		payload: (detected, afterRecord) => {
		  return {profile:"default"}
		}
	      },
	      afterRecordLimit:0,
	      restart:false,
	    },
	  },
	},
			]

		};

		/*************** DO NOT EDIT THE LINE BELOW ***************/
	if (typeof module !== "undefined") {module.exports = config;}

**Comment by eouia** [comment]
```
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response:
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
```

Somewhat weird things are there;
1) AMK2 should have not started (`[AMK2] Conversation starts.`) without activation from awakener. But it did. Usually `useWelcomeMessage` would wake up AMK2, but we removed it.

2) Hotword's life-cycle seems too short. It means, your mic is not ready to listen. 

3) `[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.` means, your mic is not ready (there could be many reasons) also.

In my conclusion; Your mic seems having some issue. 

To check, try this;

1) Remove or comment out `MMM-AssistantMk2` configuration from `config.js`
2) To make things simple, I recommend to comment out other module's configuration also.

3) Then, try this configuration, then look at what happens
```js
{
  module: "MMM-Hotword",
  position: "top_right",
  config: {
    chimeOnFinish:null,
    mic: {
      recordProgram : "arecord",  
      device        : "plughw:1",
      verbose: true,
    },
    models: [
      {
	hotwords    : "smart_mirror",
	file        : "smart_mirror.umdl",
	sensitivity : "0.5",
      },
    ],
    defaultCommand: {
      notificationExec: {
	notification: "ASSISTANT_ACTIVATE",
	payload: (detected, afterRecord) => {
          console.log("DETECTED:", detected)
	  return {profile:"default"}
	}
      },
      afterRecordLimit:0,
      restart:false,
    },
  },
},
```

**Comment by bao0720** [comment]
After I tried using this configuration, I used smart_mirror to wake it up, but the terminal appeared the following

pi@raspberrypi:~ $ cd ~/MagicMirror
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD:LPCM16] Start listening 1 channels with sample rate 16000
[HOTWORD:LPCM16] Listening 44 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 24000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes

(electron:2280): Gdk-WARNING **: 18:10:05.746: gdk_window_set_user_time called on non-toplevel

[HOTWORD:LPCM16] Listening 4000 bytes
[HOTWORD:LPCM16] Listening 4000 bytes

**Comment by eouia** [comment]
First, HOTWORD itself is working.
Have you tried to detect Hotwords like "smart mirror" ?

**Comment by bao0720** [comment]
I tried to say magicmirror to it but, it didn't respond.

**Comment by eouia** [comment]
you've said "magicmirror"? That's not registered hotword. you've registered only `smart mirror` as hotword model in your configuration. 
If you said `smart mirror`, what log says?  It should return something whether it is detected or not.

**Comment by bao0720** [comment]
I also tried to say smart mirror but, it only shows an error under the log is
Failed to load resource: the server responded with a status of 404 (Not Found).

**Comment by eouia** [comment]
Show me the log. That error is not mine.

**Comment by bao0720** [comment]
![2019-12-05-225200_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70245951-e103e300-17b1-11ea-9cc0-9222b6759719.png)

**Comment by bao0720** [comment]
Are you talking about this？

**Comment by bao0720** [comment]
![2019-12-05-225324_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70246091-1c061680-17b2-11ea-8acb-f168b7c98a86.png)

**Comment by eouia** [comment]
See the `console` tab of that screen. there would be front-end logs.

**Comment by bao0720** [comment]
![2019-12-05-225925_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70246591-f1688d80-17b2-11ea-89f4-563c9ed87c93.png)

**Comment by eouia** [comment]
Ah, Let's make things simple.

First your picture is showing front-end log. It is about module's front-end working.
But I meant the back-end log. that will be shown on your terminal. (with `npm start dev`).

So, after execution, when you say something, it will show something like this;
```
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: false }
```
If proper hotword is detected, 
```
[HOTWORD] Final Result: { detected: true, ...  }
```

**Comment by eouia** [comment]
So, I asked you what log says when you say `smart mirror` at that moment. Show me that log.

**Comment by bao0720** [comment]
I have executed npm start dev and it shows below

![2019-12-05-230654_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70247199-f5e17600-17b3-11ea-888e-35bcf944c07d.png)
![2019-12-05-230656_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70247206-f7ab3980-17b3-11ea-86ed-61a30ef55e4c.png)

**Comment by bao0720** [comment]
I have executed npm start dev and it shows below.
![2019-12-05-230954_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70247477-625c7500-17b4-11ea-84c6-51be204d41c3.png)
![2019-12-05-230955_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70247485-64becf00-17b4-11ea-8655-ba3401fb6d33.png)

**Comment by eouia** [comment]
You've said something, (`Jarvis` or any other words) right? If so, your mic volume might be too low or your pronunciation is not catchable.

**Comment by bao0720** [comment]
I'm also afraid that my pronunciation is not standard, so I used Google Translate to say to it that smart mirror and the volume is the loudest, but still the same.

**Comment by eouia** [comment]
Maybe or not. Anyway module itself looks being working by screenshot. I have no more idea about it.
