### ISSUE TITLE
Value of sensitivity

### ISSUE THREAD

**Issue by Ulrick124** [bugsounet/MMM-Hotword#98]
What is the range of sensitivity? Is the min value easily to detect hotword?

**Comment by eouia** [comment]
Max is easier to capture but the possibility of misunderstanding will rise also.

**Comment by Ulrick124** [comment]
> Min is easier to capture but the possibility of misunderstanding will rise also.

Can you explain more detail this step? I want to train my hotword:

3.Record your hotword(in this case, "volume up") 3 times on your RPI (.pmdl which is created on other device, might not work)
rec -r 16000 -c 1 -b 16 -e signed-integer 1.wav
rec -r 16000 -c 1 -b 16 -e signed-integer 2.wav
rec -r 16000 -c 1 -b 16 -e signed-integer 3.wav

I run "rec -r 16000 -c 1 -b 16 -e signed-integer 3.wav" in terminal but it has error:

     rec WARN alsa: can't encode 0-bit Unknown or not applicable
     rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory

I create a new emty file "1.wav" in pi folder OR recorder a hotwrord file named "1.wav" and paste to pi folder then run  "rec -r 16000 -c 1 -b 16 -e signed-integer 3.wav" in terminal but two ways have the same error above.

**Comment by eouia** [comment]
It seems your sound environment has some problem.
try this to check the recording and playing working.
```sh
rec test.wav 
play test.wav
```

**Comment by eouia** [comment]
hmmm.. if you are using RPI, try `arecord` instead `rec` (some options might be modified.)

**Comment by bugsounet** [comment]
*supposed solved since december...*
